name: barf-env
channels:
  - conda-forge
  #- nvidia
  #- pytorch
dependencies:
  # Only py39 works for pytorch 1.9.0:
  - python=3.9.10
  - numpy
  - scipy
  - tqdm
  - termcolor
  - easydict
  - imageio
  - ipdb
  #- cudatoolkit=11.3
  #- pytorch=1.9.0
  #- torchvision=0.10.0
  #- torchaudio=0.9.0
  - tensorboard
  - visdom
  - matplotlib
  - scikit-video
  - trimesh
  - pyyaml
  - pip
  - gdown
  - pip:
    - lpips
    - pymcubes
